stages:
  data_source:
    cmd: python src/get_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - data_given/mushrooms.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - data_given/mushrooms.csv
    outs:
    - data/processed/train_mushrooms.csv
    - data/processed/test_mushrooms.csv 

  train_and_evaluate:
    cmd: python src/train_and_evaluation.py --config=params.yaml
    deps:
    - data/processed/train_mushrooms.csv
    - data/processed/test_mushrooms.csv
    - src/train_and_evaluation.py
    params:
    - estimator.SVC.params.cache_size
    - estimator.SVC.params.degree
    
    metrics:
    - reports/scores.json:
        cache: false
    - reports/params.json:
        cache: false
    outs:
    - models/model.pkl